#!/bin/bash
# Install Fail2ban on many distributions including Pardus
# Supports: Ubuntu/Debian/Pardus, CentOS/RHEL/Fedora/AlmaLinux, Alpine, Arch
set -e

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
NC='\033[0m' # No Color

detect_os() {
    if [ -f /etc/os-release ]; then
        . /etc/os-release
        OS=${ID:-unknown}
        VERSION=${VERSION_ID:-unknown}
    elif type lsb_release >/dev/null 2>&1; then
        OS=$(lsb_release -si | tr '[:upper:]' '[:lower:]')
        VERSION=$(lsb_release -sr)
    elif [ -f /etc/redhat-release ]; then
        OS="rhel"
        VERSION=$(grep -oE '[0-9]+\.[0-9]+' /etc/redhat-release)
    elif [ -f /etc/alpine-release ]; then
        OS="alpine"
        VERSION=$(cat /etc/alpine-release)
    else
        OS=$(uname -s | tr '[:upper:]' '[:lower:]')
        VERSION=$(uname -r)
    fi
}

install_fail2ban() {
    echo -e "${GREEN}Detected system: $OS $VERSION${NC}"

    case "$OS" in
        ubuntu|debian|pardus|linuxmint|pop|neon)   # ← added pardus + popular derivatives
            sudo apt update
            if ! command -v rsyslog >/dev/null 2>&1; then
                echo -e "${YELLOW}rsyslog not found → installing...${NC}"
                sudo apt install -y rsyslog
            else
                echo -e "${GREEN}rsyslog already installed.${NC}"
            fi
            sudo apt install -y fail2ban
            ;;

        centos|rhel|fedora|almalinux|rocky)
            if [[ "$OS" == "rhel" || "$OS" == "centos" ]] && [[ "${VERSION%%.*}" -ge 8 ]]; then
                sudo dnf install -y epel-release
                sudo dnf install -y fail2ban
            elif [[ "$OS" == "fedora" ]]; then
                sudo dnf install -y fail2ban
            else
                sudo yum install -y epel-release
                sudo yum install -y fail2ban
            fi
            ;;

        alpine)
            sudo apk add --no-cache fail2ban
            ;;

        arch|manjaro|endeavour)
            sudo pacman -Sy --noconfirm fail2ban
            ;;

        *)
            echo -e "${RED}Unsupported distribution: $OS${NC}"
            echo "You can try manually: sudo apt install fail2ban  (if debian-based)"
            exit 1
            ;;
    esac
}

configure_fail2ban() {
    echo -e "${GREEN}Configuring Fail2ban...${NC}"

    local FAIL2BAN_CONF="/etc/fail2ban/jail.local"

    # Choose ban action according to active firewall
    if systemctl is-active --quiet firewalld 2>/dev/null; then
        BAN_ACTION="firewallcmd-ipset"
    elif command -v ufw >/dev/null && ufw status >/dev/null 2>&1; then
        BAN_ACTION="ufw"
    else
        BAN_ACTION="iptables-multiport"   # ← more common & safer default than allports
    fi

    # Choose correct auth log (most debian-based → auth.log, some older/centos → secure)
    local LOG_FILE="/var/log/auth.log"
    if [ -f "/var/log/secure" ] && [ ! -s "/var/log/auth.log" ]; then
        LOG_FILE="/var/log/secure"
    fi
    [ -f "$LOG_FILE" ] || sudo touch "$LOG_FILE"

    sudo bash -c "cat > $FAIL2BAN_CONF" <<EOF
# Generated by fail2ban install script - $(date)

[DEFAULT]
bantime  = 10m
findtime = 10m
maxretry = 5
banaction = $BAN_ACTION
action = %(action_mwl)s
ignoreip = 127.0.0.1/8 ::1 your-trusted-ip-here-if-any

[sshd]
enabled   = true
filter    = sshd
port      = ssh
maxretry  = 5
findtime  = 10m
bantime   = 3600
logpath   = $LOG_FILE
EOF

    echo -e "${GREEN}jail.local created with banaction=$BAN_ACTION and log=$LOG_FILE${NC}"
}

start_service() {
    echo -e "${GREEN}Starting & enabling Fail2ban...${NC}"

    if command -v systemctl >/dev/null; then
        sudo systemctl enable fail2ban
        sudo systemctl restart fail2ban
        sudo systemctl status fail2ban --no-pager || true
    elif command -v rc-service >/dev/null; then
        # Alpine OpenRC
        sudo rc-update add fail2ban default
        sudo rc-service fail2ban start
        sudo rc-service fail2ban status || true
    else
        echo -e "${YELLOW}Don't know how to start service automatically on this init system.${NC}"
        echo "Please start fail2ban manually."
    fi

    echo -e "${GREEN}Fail2ban installation finished.${NC}"
    echo "Check banned IPs after some time:   sudo fail2ban-client status sshd"
}

main() {
    detect_os
    install_fail2ban
    configure_fail2ban
    start_service
}

main "$@"